grpc:
  port: 5462
  check:
    host: host.docker.internal
http:
  port: 5463
  check:
    host: host.docker.internal
consul:
  disabled: false
  scheme: http
  host: 127.0.0.1
  port: 8500
  dc: dc1
  check:
    interval: 10s
apmserver:
  name: elasticsearch-apm-server
  tag: local
  dc: dc1
