{
 "title": "testservice - main",
 "description": "testservice internal metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(go_memstats_alloc_bytes,job)"
   },
   { "name": "percentile", "label": "percentile", "query": "0.25,0.5,0.75,0,95,0,99" }
  ]
 },
 "panels": [
  {
   "title": "Total memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\"}",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "Detailed memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$job\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$job\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "GC duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(go_gc_duration_seconds_sum{job=\"$job\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}